#!/usr/bin/env python3
"""Materialize CI-only signing inputs without printing secrets or caching them."""
import argparse
import base64
import os
from pathlib import Path

HEADER = "# Generated by scripts/ci-configure.py\n"


def property_value(value):
    # java.util.Properties.load(InputStream) uses ISO-8859-1 and backslash escapes.
    result = []
    for char in value:
        if char == "\\":
            result.append("\\\\")
        elif char == "\n":
            result.append("\\n")
        elif char == "\r":
            result.append("\\r")
        elif char == "\t":
            result.append("\\t")
        elif char in " =:#!":
            result.append("\\" + char)
        elif not 32 <= ord(char) <= 126:
            for offset in range(0, len(char.encode("utf-16-be")), 2):
                unit = char.encode("utf-16-be")[offset:offset + 2]
                result.append("\\u" + unit.hex())
        else:
            result.append(char)
    return "".join(result)


def write_private(path, data):
    descriptor = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "wb") as stream:
        stream.write(data)


def configure(root, temp, env):
    required = ("ANDROID_KEYSTORE_BASE64", "ANDROID_KEYSTORE_PASSWORD", "ANDROID_KEY_ALIAS",
                "ANDROID_KEY_PASSWORD", "TELEGRAM_API_ID", "TELEGRAM_API_HASH", "ANDROID_SDK_ROOT")
    if any(not env.get(name) for name in required):
        raise ValueError("Required CI signing or Telegram build secrets are missing")
    if not env["TELEGRAM_API_ID"].isdigit():
        raise ValueError("Invalid Telegram API ID")
    keystore = base64.b64decode(env["ANDROID_KEYSTORE_BASE64"], validate=True)
    if not keystore:
        raise ValueError("Empty release keystore")
    signing_dir = temp / "moegramx-signing"
    if (root / "local.properties").exists() or signing_dir.exists():
        raise ValueError("Refusing to overwrite an existing build configuration")
    signing_dir.mkdir(mode=0o700)
    write_private(signing_dir / "release.p12", keystore)
    signing = {
        "keystore.file": str(signing_dir / "release.p12"),
        "keystore.password": env["ANDROID_KEYSTORE_PASSWORD"],
        "key.alias": env["ANDROID_KEY_ALIAS"],
        "key.password": env["ANDROID_KEY_PASSWORD"],
    }
    local = {
        "sdk.dir": env["ANDROID_SDK_ROOT"],
        "keystore.file": str(signing_dir / "signing.properties"),
        "app.id": "com.ayx.mgx",
        "app.name": "moegramX",
        "app.experimental": "false",
        "app.download_url": "https://github.com/Entermage/moeGramX-ghost/actions/workflows/android-arm64.yml",
        "app.sources_url": "https://github.com/Entermage/moeGramX-ghost",
        "tgx.extension": "none",
        "telegram.api_id": env["TELEGRAM_API_ID"],
        "telegram.api_hash": env["TELEGRAM_API_HASH"],
    }
    for path, properties in ((signing_dir / "signing.properties", signing), (root / "local.properties", local)):
        content = HEADER + "".join(key + "=" + property_value(value) + "\n" for key, value in properties.items())
        write_private(path, content.encode("ascii"))


def cleanup(root, temp):
    local = root / "local.properties"
    if local.exists() and not local.is_symlink() and local.read_text(encoding="ascii").startswith(HEADER):
        local.unlink()
    signing_dir = temp / "moegramx-signing"
    if signing_dir.is_symlink():
        raise ValueError("Refusing to follow a signing directory symlink")
    if signing_dir.is_dir():
        for name in ("release.p12", "signing.properties"):
            (signing_dir / name).unlink(missing_ok=True)
        signing_dir.rmdir()


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cleanup", action="store_true")
    args = parser.parse_args()
    if os.environ.get("GITHUB_ACTIONS") != "true":
        raise SystemExit("This script only runs inside GitHub Actions")
    root = Path(os.environ["GITHUB_WORKSPACE"]).resolve()
    temp = Path(os.environ["RUNNER_TEMP"]).resolve()
    if root != Path.cwd().resolve() or not temp.is_dir():
        raise SystemExit("Unexpected CI workspace or temporary directory")
    try:
        if args.cleanup:
            cleanup(root, temp)
        else:
            configure(root, temp, os.environ)
    except (ValueError, OSError):
        # Do not put secret values, parser errors or exception locals into public logs.
        raise SystemExit("CI configuration failed; check required secrets and file permissions") from None
    print("CI signing files removed" if args.cleanup else "CI release configuration prepared")


if __name__ == "__main__":
    main()
